apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime
  labels:
    app: realtime
spec:
  selector:
    matchLabels:
      app: realtime
  replicas: 2
  template:
    metadata:
      labels:
        app: realtime
    spec:
      containers:
      - name: realtime
        image: gbaeke/flux-rt
        livenessProbe:
          httpGet:
            path: /index.html
            port: 8080
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080
        env:
        - name: REDISHOST
          value: "$(REDISSERVICE).$(REDISNAMESPACE):6379"
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: realtime
  labels:
    app: realtime
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: realtime
